"""initial schema: knowledge, episodes, procedures, archive

Revision ID: ea238bc9f085
Revises: 
Create Date: 2026-04-17 16:04:04.716579
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea238bc9f085'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archive',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('original_table', sa.String(length=50), nullable=False),
    sa.Column('original_id', sa.String(), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('episodes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('actions', sa.Text(), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('day_of_week', sa.String(length=20), nullable=False),
    sa.Column('time_of_day', sa.String(length=20), nullable=False),
    sa.Column('device', sa.String(length=100), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('learned', sa.Text(), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('linked_episode_ids', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_accessed', sa.DateTime(), nullable=False),
    sa.Column('source_device', sa.String(length=100), nullable=False),
    sa.Column('source_session', sa.String(length=100), nullable=False),
    sa.Column('decay_score', sa.Float(), nullable=False),
    sa.Column('tags', sa.Text(), nullable=False),
    sa.Column('previous_values', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('procedures',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('trigger_description', sa.Text(), nullable=False),
    sa.Column('steps', sa.Text(), nullable=False),
    sa.Column('times_executed', sa.Integer(), nullable=False),
    sa.Column('times_detected', sa.Integer(), nullable=False),
    sa.Column('detection_threshold', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_executed', sa.DateTime(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=False),
    sa.Column('trigger_type', sa.String(length=30), nullable=False),
    sa.Column('trigger_conditions', sa.Text(), nullable=False),
    sa.Column('target_devices', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('procedures')
    op.drop_table('knowledge')
    op.drop_table('episodes')
    op.drop_table('archive')
    # ### end Alembic commands ###
